### ISSUE TITLE
Error when calling npm-start

### ISSUE THREAD

**Issue by actanasoiu** [onehungrymind/ng2-rest-app#2]
I'm getting the following error when calling 'npm start' and because of that 4200 port is not working.

I'm using:
npm version 3.10.6
node version 4.5.0

This is a sample of my CMD line
[1] W:\Training\Angular 2\Building Awesome Web Apps with Angular 2\ng2-rest-app\node_modules\@ngtools\json-schema\src\schema-class-factory.js:34
[1]             result.push(...indices);
[1]                         ^^^
[1]
[1] SyntaxError: Unexpected token ...
[1]     at exports.runInThisContext (vm.js:53:16)
[1]     at Module._compile (module.js:373:25)
[1]     at Object.Module._extensions..js (module.js:416:10)
[1]     at Module.load (module.js:343:32)
[1]     at Function.Module._load (module.js:300:12)
[1]     at Module.require (module.js:353:17)
[1]     at require (internal/module.js:12:17)
[1]     at Object.<anonymous> (W:\Training\Angular 2\Building Awesome Web Apps with Angular 2\ng2-rest-app\node_modules\@ngtools\json-schema\src\index.js:3:30)
[1]     at Module._compile (module.js:409:26)
[1]     at Object.Module._extensions..js (module.js:416:10)
[1] ng serve exited with code 1
[0]
[0] > ng2-rest-app@0.0.0 server W:\Training\Angular 2\Building Awesome Web Apps with Angular 2\ng2-rest-app
[0] > json-server --watch server/api/db.json
[0]
[0]
[0]   \{^_^}/ hi!
[0]
[0]   Loading server/api/db.json
[0]   Done
[0]
[0]   Resources
[0]   http://localhost:3000/items
[0]   http://localhost:3000/widgets
[0]
[0]   Home
[0]   http://localhost:3000
[0]
[0]   Type s + enter at any time to create a snapshot of the database
[0]   Watching...

**Comment by mrxico88** [comment]
I got the same problem when running this npm start :(

**Comment by huntermacd** [comment]
Looks like one or more of the Angular CLI files makes use of [ES6 default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters), which [aren't supported in Node below version 6.4.0](http://node.green/#ES2015-syntax-default-function-parameters). Upgrading your version of Node to 6.4.0 or higher should do the trick. The docs for this repo should indicate that either a higher version of Node should be used or a lower version of Angular CLI.

**Comment by jdgarvey** [comment]
@huntermacd 
Thanks for pointing this out, we've updated the `Dependencies` section of the README to avoid confusion 👍
